apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-helm-test"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: helm-test
          image: curlimages/curl:8.5.0
          command: ["/bin/sh","-c"]
          args:
            - |
              sleep 15
              curl -s http://{{ .Release.Name }}:8080/health
              curl -s http://kube-prometheus-stack-prometheus:9090/api/v1/query?query=up | grep success
